apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pv-claim
  labels:
    app: nginx
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: rook-block
  resources:
    requests:
      storage: 1Gi
