apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: sbellan/dwsample:1.0
        command: ["/deployments/run-java.sh", "consumer"]
        ports:
        - containerPort: 8080