apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: sbellan/dwsample:1.1
        command: ["/deployments/run-java.sh", "producer"]
        ports:
        - containerPort: 8080